create or replace TABLE BHATBHATENI.TGT.DWH_F_BHATBHATENI_AGG_SLS_PLC_MONTH_T (
	AGG_ID NUMBER(38,0) NOT NULL,
	AGG_KEY NUMBER(38,0) autoincrement,
	STORE_ID NUMBER(38,0),
	STORE VARCHAR(16777216),
	PRODUCT_ID NUMBER(38,0),
	TRANSACTION_TIME NUMBER(38,0),
	TOTAL_QUANTITY NUMBER(38,0),
	TOTAL_AMOUNT NUMBER(20,2),
	ACTIVE_FLAG VARCHAR(2),
	CREATED_TS VARCHAR(16777216),
	UPDATED_TS TIMESTAMP_NTZ(9),
	primary key (AGG_ID)
);

create or replace TABLE BHATBHATENI.TMP.TMP_F_BHATBHATENI_AGG_SLS_PLC_MONTH_T (
	ID NUMBER(38,0) NOT NULL,
	STORE_ID NUMBER(38,0) NOT NULL,
	PRODUCT_ID NUMBER(38,0) NOT NULL,
	CUSTOMER_ID NUMBER(38,0),
	TRANSACTION_MONTH VARCHAR(16777216),
	TOTAL_QUANTITY NUMBER(38,0),
	TOTAL_AMOUNT NUMBER(20,2),
	TOTAL_DISCOUNT NUMBER(20,2),
	primary key (ID)
);
create or replace TABLE BHATBHATENI.STG.STG_F_BHATBHATENI_AGG_SLS_PLC_MONTH_T (
	ID NUMBER(38,0) NOT NULL,
	STORE_ID NUMBER(38,0) NOT NULL,
	PRODUCT_ID NUMBER(38,0) NOT NULL,
	CUSTOMER_ID NUMBER(38,0),
	TRANSACTION_DAY TIMESTAMP_NTZ(9),
	QUANTITY NUMBER(38,0),
	AMOUNT NUMBER(20,2),
	DISCOUNT NUMBER(20,2),
	primary key (ID)
);
